name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  RUSTFLAGS: "-D warnings"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Format, lint, build, test
        run: cargo fmt --check && cargo clippy -- -D warnings && cargo build && cargo test
